ACCOUNT_TABLE_NAME = "Accounts"
TRANSACTION_COLUMN = "Transaction_count"
AMOUNT_COLUMN = "Amount"
HOMELOAN_COLUMN = "Home_loan"
BANK_INTEREST = 2
LOAN_INTEREST = 5
BANK_ID = "MONARCHY-00001"
MAX_HOME_LOAN_AMOUNT = 800000

DATABASE_NAME = "MonarchyBank.db"
ACCOUNT_TABLE_NAME = "Accounts"
HOMELOAN_TABLE_NAME = "HomeLoan"